// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://enxqkgozdgyqraurubtc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVueHFrZ296ZGd5cXJhdXJ1YnRjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc0NjQ3MzksImV4cCI6MjA1MzA0MDczOX0.Pxo2X4wIvdPGpxoDSbFt5zFp3Siu3oxEbKsnooF-qQg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);